<!-- Cart Container  -->
<!--<div class="container">
    <div class="cart_list"></div>
</div>-->
<!-- Cart Container  -->

<!-- ANGULAR  -->
  <!--<h2>JavaScript-проекты</h2>
    <div ng-view></div>
    <input type="text" ng-model="search" class="search-query" placeholder="Search">
    <table>
      <thead>
      <tr>
        <th>Проект</th>
        <th>Описание</th>
        <th><a href="#/new"><i class="icon-plus-sign"></i></a></th>
      </tr>
      </thead>
      <tbody>
      <tr ng-repeat="project in projects | filter:search | orderBy:'name'">
        <td><a href="{{project.site}}" target="_blank">{{project.name}}</a></td>
        <td>{{project.description}}</td>
        <td>
          <a href="#/edit/{{project._id.$oid}}"><i class="icon-pencil"></i></a>
        </td>
      </tr>
      </tbody>
    </table>-->
<!-- ANGULAR  -->

<?php























